trigger: none
pr: none

pool:
  vmImage: 'windows-latest'
variables:
  Versao: $(version)
  BUILD_ID: $(Build.BuildNumber)

steps:
- checkout: none

- powershell: |
      echo $env:Versao; $env:BUILD_ID
