# Dummy pipeline to test System access token

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: echo This script could use $SYSTEM_ACCESSTOKEN
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - powershell: Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
  - script: echo The script could use $SYSTEM_ACCESSTOKEN
    env:
      SYSTEM_ACESSTOKEN: $(System.AccessToken)