trigger: none
pr: none
resources:
    repositories:
        - repository: dummy
          name: DummyProject
          type: git
pool:
  vmImage: ubuntu-latest

# Build tags example
steps:
  - checkout: dummy
  - bash: |
        echo "hello world" > newfile.log
        git add .
        git commit -m "dummy commit"
        git status