trigger: none
pr: none
resources:
    repositories:
        - repository: dummy
          name: DummyProject
pool:
  vmImage: ubuntu-latest

# Build tags example
steps:
  - checkout: dummy
  - bash: |
        git status