# Push Force Test

trigger: none
pr: none

resources:
    repositories:
        - repository: dummy
          name: DummyProject

pool:
    vmImage: 'ubuntu-latest'

steps:
    - checkout: dummy
    - bash: |
        echo "HelloWorld" > newfile.log
        git add .
        git commit -m "new File"
        git push origin master
