trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

steps:

- pwsh: |
      $deployDate = get-date -format 'dd/MM/yyy';
      write-output "##vso[task.setvariable variable=deployDate]$deployDate";
      $mailBody = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Atenção:.md</title><style></style></head><body id="preview">
      <h1 class="code-line" data-line-start=0 data-line-end=1><a id="Ateno_0"></a>Atenção:</h1>
      <p class="has-line-data" data-line-start="2" data-line-end="3">O código de produção foi atualizado no VSTS após Deploy, realizado hoje ($deployDate).</p>
      <p class="has-line-data" data-line-start="4" data-line-end="5"><code>Master</code> do repositório $(Build.Repository.Name) atualizado.</p>
      <h4 class="code-line" data-line-start=6 data-line-end=7><a id="Favor_realizar_o_pull_nos_branches_em_andamento_de_vocs_6"></a>Favor realizar o alinhamento das branches em andamento com a ultima atualização da master.</h4>
      <blockquote><p class="has-line-data" data-line-start="8" data-line-end="9">Nota: Essa é uma mensagem automatica favor não responder</p>
      </blockquote>
      </body></html>' -replace "\r\n|\r|\n/gm";
      write-output '##vso[task.setvariable variable=message]$mailBody'
  displayName: define mailBody

- powershell: |
      echo $env:DEPLOYDATE
      write-output $env:MAILBODY;