trigger: 
 - master
pr: none


variables:
    pipelineScopeVariable: "[MyProject] - VSTS -"

steps:
- checkout: none
# Append variable string test

- powershell: write-output "##vso[task.setvariable variable=subject]testValue"
        
- powershell: | 
      write-output "form 1" $(subject)
      write-output "form 2"
      write-output $env:SUBJECT
      gci Env:

- powershell: |
        $pipelineScopeVariable = $env:PIPELINESCOPEVARIABLE + "MYtaG-1.0"
        write-output "##vso[task.setvariable variable=pipelineScopeVariable]$pipelineScopeVariable"
        write-output $(pipelineScopeVariable)

- powershell: write-output $(pipelineScopeVariable)
        