trigger: none
pr: none


variables:
    pipelineScopeVariable: "[MyProject] - VSTS -"

steps:
- checkout: none
# Append variable string test

- powershell: write-output "##vso[task.setvariable variable=subject]testValue"
        
- powershell: | 
      write $(subject)
      write $env:subject
      write-output $env:subject
      write-output $(subject)
- powershell: write $(subject)
- powershell: write-output $(subject)