trigger: 
 - master
pr: none


variables:
    pipelineScopeVariable: "[MyProject] - VSTS -"

steps:
- checkout: none
# Append variable string test

- powershell: write-output "##vso[task.setvariable variable=subject]testValue"
        
- powershell: | 
      write-output "$(subject)" $(subject)
      write-output "$env:subject" $env:subject
      gci Env:
- powershell: write-output $(subject)